// <auto-generated />
namespace QRefTrain3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _13_addingDateToResults : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_13_addingDateToResults));

        string IMigrationMetadata.Id
        {
            get { return "201708181342056_1.3_addingDateToResults"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
