// <auto-generated />
namespace QRefTrain3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _16_wtf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_16_wtf));

        string IMigrationMetadata.Id
        {
            get { return "201708231128561_1.6_wtf"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
