// <auto-generated />
namespace QRefTrain3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _18_ChangeQuestionAnswers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_18_ChangeQuestionAnswers));
        
        string IMigrationMetadata.Id
        {
            get { return "201802181523382_1.8_ChangeQuestionAnswers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
