// <auto-generated />
namespace QRefTrain3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PasswordLenghtUp32 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PasswordLenghtUp32));
        
        string IMigrationMetadata.Id
        {
            get { return "201805240903184_PasswordLenghtUp32"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
