//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRefResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QuestionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuestionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QRefTrain3.App_GlobalResources.QuestionResource", typeof(QuestionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to hoops.
        /// </summary>
        public static string backToHoops {
            get {
                return ResourceManager.GetString("backToHoops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue card.
        /// </summary>
        public static string BlueCard {
            get {
                return ResourceManager.GetString("BlueCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No penalty.
        /// </summary>
        public static string NoPenalty {
            get {
                return ResourceManager.GetString("NoPenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players that already held a ball may keep holding it..
        /// </summary>
        public static string QuestionActingDuringBroomsDownExplanation {
            get {
                return ResourceManager.GetString("QuestionActingDuringBroomsDownExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for moving or taking hold of a ball during a brooms down ?.
        /// </summary>
        public static string QuestionActingDuringBroomsDownText {
            get {
                return ResourceManager.GetString("QuestionActingDuringBroomsDownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for an interposition ball interference ?.
        /// </summary>
        public static string QuestionBallInterferenceText {
            get {
                return ResourceManager.GetString("QuestionBallInterferenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for intentionally and illegally blocking a score ?.
        /// </summary>
        public static string QuestionBlockingScoringQuaffleText {
            get {
                return ResourceManager.GetString("QuestionBlockingScoringQuaffleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string QuestionChangeAfterBroomsDownExplanation {
            get {
                return ResourceManager.GetString("QuestionChangeAfterBroomsDownExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for changing position or location after brooms down, at the beginning of a match ?.
        /// </summary>
        public static string QuestionChangeAfterBroomsDownText {
            get {
                return ResourceManager.GetString("QuestionChangeAfterBroomsDownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A helpless receiver is defined as a receiver who is in the process of catching a ball that is in the air..
        /// </summary>
        public static string QuestionChargeTackleHelplessReceiverExplanation {
            get {
                return ResourceManager.GetString("QuestionChargeTackleHelplessReceiverExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is a penalty a charge or tackle on a helpless receiver ?.
        /// </summary>
        public static string QuestionChargeTackleHelplessReceiverText {
            get {
                return ResourceManager.GetString("QuestionChargeTackleHelplessReceiverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for making an illegal contact while knocked out ?.
        /// </summary>
        public static string QuestionContactWhenKOText {
            get {
                return ResourceManager.GetString("QuestionContactWhenKOText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team must change as few players as possible.
        /// </summary>
        public static string QuestionCorrectingIllegalSetPlayerAnswer1 {
            get {
                return ResourceManager.GetString("QuestionCorrectingIllegalSetPlayerAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team may change any number of player, as ling as this result in a legal set of players.
        /// </summary>
        public static string QuestionCorrectingIllegalSetPlayerAnswer2 {
            get {
                return ResourceManager.GetString("QuestionCorrectingIllegalSetPlayerAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team cannot change players immediatly, but must sub players as soon as the game restart.
        /// </summary>
        public static string QuestionCorrectingIllegalSetPlayerAnswer3 {
            get {
                return ResourceManager.GetString("QuestionCorrectingIllegalSetPlayerAnswer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What of the following is true when correcting an illegal set of player ?.
        /// </summary>
        public static string QuestionCorrectingIllegalSetPlayerText {
            get {
                return ResourceManager.GetString("QuestionCorrectingIllegalSetPlayerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for a dangerous kick or a kick to an opponent ?.
        /// </summary>
        public static string QuestionDangerousKickText {
            get {
                return ResourceManager.GetString("QuestionDangerousKickText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for illegaly acting on a dead quaffle ?.
        /// </summary>
        public static string QuestionDeadQuafflePlayText {
            get {
                return ResourceManager.GetString("QuestionDeadQuafflePlayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A team may decline any snitch catch.
        /// </summary>
        public static string QuestionDecliningCatchAnswer1 {
            get {
                return ResourceManager.GetString("QuestionDecliningCatchAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The catch can be just after a goal and before the referee confirmed the goal as good.
        /// </summary>
        public static string QuestionDecliningCatchAnswer2 {
            get {
                return ResourceManager.GetString("QuestionDecliningCatchAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The catch occured after a goal event (good or otherwise), and before the referee adjust his call for this event.
        /// </summary>
        public static string QuestionDecliningCatchAnswer3 {
            get {
                return ResourceManager.GetString("QuestionDecliningCatchAnswer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The change in score must change whether the catch would end the period in a tie.
        /// </summary>
        public static string QuestionDecliningCatchAnswer4 {
            get {
                return ResourceManager.GetString("QuestionDecliningCatchAnswer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What of the following are true for a team that wants to decline a snitch catch ?.
        /// </summary>
        public static string QuestionDecliningCatchText {
            get {
                return ResourceManager.GetString("QuestionDecliningCatchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A second blue card is upgraded to a yellow card.
        /// </summary>
        public static string QuestionDefBlueCardsAnswer1 {
            get {
                return ResourceManager.GetString("QuestionDefBlueCardsAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any ball acted upon or prevented to get by the fouling player is turned over.
        /// </summary>
        public static string QuestionDefBlueCardsAnswer2 {
            get {
                return ResourceManager.GetString("QuestionDefBlueCardsAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quaffle is turned over.
        /// </summary>
        public static string QuestionDefBlueCardsAnswer3 {
            get {
                return ResourceManager.GetString("QuestionDefBlueCardsAnswer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player is released after a minute.
        /// </summary>
        public static string QuestionDefBlueCardsAnswer4 {
            get {
                return ResourceManager.GetString("QuestionDefBlueCardsAnswer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player is released after getting scored.
        /// </summary>
        public static string QuestionDefBlueCardsAnswer5 {
            get {
                return ResourceManager.GetString("QuestionDefBlueCardsAnswer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which of the followings are true for a blue card call ?.
        /// </summary>
        public static string QuestionDefBlueCardsText {
            get {
                return ResourceManager.GetString("QuestionDefBlueCardsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any ball acted upon or prevented to get by the fouling player is turned over.
        /// </summary>
        public static string QuestionDefRedCardsAnswer1 {
            get {
                return ResourceManager.GetString("QuestionDefRedCardsAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quaffle is turned over.
        /// </summary>
        public static string QuestionDefRedCardsAnswer2 {
            get {
                return ResourceManager.GetString("QuestionDefRedCardsAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Player is released after a minute.
        /// </summary>
        public static string QuestionDefRedCardsAnswer3 {
            get {
                return ResourceManager.GetString("QuestionDefRedCardsAnswer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Player is released after two minutes.
        /// </summary>
        public static string QuestionDefRedCardsAnswer4 {
            get {
                return ResourceManager.GetString("QuestionDefRedCardsAnswer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Player is released after getting scored.
        /// </summary>
        public static string QuestionDefRedCardsAnswer5 {
            get {
                return ResourceManager.GetString("QuestionDefRedCardsAnswer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since the red carded player may not play the match again, it is a different player that must go into the penalty box and be released..
        /// </summary>
        public static string QuestionDefRedCardsExplanation {
            get {
                return ResourceManager.GetString("QuestionDefRedCardsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which of the followings are true for a red card call ?.
        /// </summary>
        public static string QuestionDefRedCardsText {
            get {
                return ResourceManager.GetString("QuestionDefRedCardsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A second yellow card is upgraded to a red card.
        /// </summary>
        public static string QuestionDefYellowCardsAnswer1 {
            get {
                return ResourceManager.GetString("QuestionDefYellowCardsAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any ball acted upon or prevented to get by the fouling player is turned over.
        /// </summary>
        public static string QuestionDefYellowCardsAnswer2 {
            get {
                return ResourceManager.GetString("QuestionDefYellowCardsAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quaffle is turned over.
        /// </summary>
        public static string QuestionDefYellowCardsAnswer3 {
            get {
                return ResourceManager.GetString("QuestionDefYellowCardsAnswer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player is released after a minute.
        /// </summary>
        public static string QuestionDefYellowCardsAnswer4 {
            get {
                return ResourceManager.GetString("QuestionDefYellowCardsAnswer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player is released after getting scored.
        /// </summary>
        public static string QuestionDefYellowCardsAnswer5 {
            get {
                return ResourceManager.GetString("QuestionDefYellowCardsAnswer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which of the followings are true for a yellow card call ?.
        /// </summary>
        public static string QuestionDefYellowCardsText {
            get {
                return ResourceManager.GetString("QuestionDefYellowCardsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for a delay of game ?.
        /// </summary>
        public static string QuestionDelayOfGameText {
            get {
                return ResourceManager.GetString("QuestionDelayOfGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for intentionnaly dislodging a hoop ?.
        /// </summary>
        public static string QuestionDislodgeHoopIntentionnalyText {
            get {
                return ResourceManager.GetString("QuestionDislodgeHoopIntentionnalyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for recklessly dislodging a hoop ?.
        /// </summary>
        public static string QuestionDislodgeHoopRecklessText {
            get {
                return ResourceManager.GetString("QuestionDislodgeHoopRecklessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for unintentionally dislodging hoops repeatedly ?.
        /// </summary>
        public static string QuestionDislodgeHoopRepeatedlyText {
            get {
                return ResourceManager.GetString("QuestionDislodgeHoopRepeatedlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for an egregious unsportsmanlike conduct ?.
        /// </summary>
        public static string QuestionEgregiousUnsportsmanlikeConductText {
            get {
                return ResourceManager.GetString("QuestionEgregiousUnsportsmanlikeConductText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for encroaching the pitch ?.
        /// </summary>
        public static string QuestionEncroachingPitchText {
            get {
                return ResourceManager.GetString("QuestionEncroachingPitchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for a failure to avoid a propelled quaffle ?.
        /// </summary>
        public static string QuestionFailedAvoidQuaffleText {
            get {
                return ResourceManager.GetString("QuestionFailedAvoidQuaffleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat procedure.
        /// </summary>
        public static string QuestionFailKOProcedureAnswer1 {
            get {
                return ResourceManager.GetString("QuestionFailKOProcedureAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violating it multiple times or willingly increases the penalty..
        /// </summary>
        public static string QuestionFailKOProcedureExplanation {
            get {
                return ResourceManager.GetString("QuestionFailKOProcedureExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for violating the knockout procedure ?.
        /// </summary>
        public static string QuestionFailKOProcedureText {
            get {
                return ResourceManager.GetString("QuestionFailKOProcedureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player may finish the play before adjusting the headband.
        /// </summary>
        public static string QuestionFailReplaceHeadbandExplanation {
            get {
                return ResourceManager.GetString("QuestionFailReplaceHeadbandExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for failing to replace a lost headband ?.
        /// </summary>
        public static string QuestionFailReplaceHeadbandText {
            get {
                return ResourceManager.GetString("QuestionFailReplaceHeadbandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnover and immediatly send a seeker.
        /// </summary>
        public static string QuestionFailSendSeekerPlayerAnswer1 {
            get {
                return ResourceManager.GetString("QuestionFailSendSeekerPlayerAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue card for the speaking captain.
        /// </summary>
        public static string QuestionFailSendSeekerPlayerAnswer2 {
            get {
                return ResourceManager.GetString("QuestionFailSendSeekerPlayerAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow card for the speaking captain.
        /// </summary>
        public static string QuestionFailSendSeekerPlayerAnswer3 {
            get {
                return ResourceManager.GetString("QuestionFailSendSeekerPlayerAnswer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red card for the speaking captain.
        /// </summary>
        public static string QuestionFailSendSeekerPlayerAnswer4 {
            get {
                return ResourceManager.GetString("QuestionFailSendSeekerPlayerAnswer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for intentionnaly failing to send a seeker into the game ?.
        /// </summary>
        public static string QuestionFailSendSeekerPlayerText {
            get {
                return ResourceManager.GetString("QuestionFailSendSeekerPlayerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for illegally contacting an opponent with a held bludger.
        /// </summary>
        public static string QuestionFakeBeatText {
            get {
                return ResourceManager.GetString("QuestionFakeBeatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for a false start ?.
        /// </summary>
        public static string QuestionFalseStartText {
            get {
                return ResourceManager.GetString("QuestionFalseStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for feigning an injury ?.
        /// </summary>
        public static string QuestionFeigningInjuryText {
            get {
                return ResourceManager.GetString("QuestionFeigningInjuryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a placeholder for this question&apos;s text. If you find the answer, congrats..
        /// </summary>
        public static string QuestionGifTestQuestionText {
            get {
                return ResourceManager.GetString("QuestionGifTestQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 meters.
        /// </summary>
        public static string QuestionGoalLineMetersAnswer1 {
            get {
                return ResourceManager.GetString("QuestionGoalLineMetersAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.5 meters.
        /// </summary>
        public static string QuestionGoalLineMetersAnswer2 {
            get {
                return ResourceManager.GetString("QuestionGoalLineMetersAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18 meters.
        /// </summary>
        public static string QuestionGoalLineMetersAnswer3 {
            get {
                return ResourceManager.GetString("QuestionGoalLineMetersAnswer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At which distance is the goal line from the midfield line ?.
        /// </summary>
        public static string QuestionGoalLineMetersText {
            get {
                return ResourceManager.GetString("QuestionGoalLineMetersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 yards.
        /// </summary>
        public static string QuestionGoalLineYardAnswer1 {
            get {
                return ResourceManager.GetString("QuestionGoalLineYardAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.5 yards.
        /// </summary>
        public static string QuestionGoalLineYardAnswer2 {
            get {
                return ResourceManager.GetString("QuestionGoalLineYardAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18 yards.
        /// </summary>
        public static string QuestionGoalLineYardAnswer3 {
            get {
                return ResourceManager.GetString("QuestionGoalLineYardAnswer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At which distance is the goal line from the midfield line ?.
        /// </summary>
        public static string QuestionGoalLineYardText {
            get {
                return ResourceManager.GetString("QuestionGoalLineYardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The score is counter as good for the fouled team.
        /// </summary>
        public static string QuestionGoaltendingAnswer1 {
            get {
                return ResourceManager.GetString("QuestionGoaltendingAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for goaltending ?.
        /// </summary>
        public static string QuestionGoaltendingText {
            get {
                return ResourceManager.GetString("QuestionGoaltendingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for willfully ignoring being knocked out ?.
        /// </summary>
        public static string QuestionIgnoreKnockoutText {
            get {
                return ResourceManager.GetString("QuestionIgnoreKnockoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is also true for assist refs, snitch ref and snitch runner..
        /// </summary>
        public static string QuestionIgnoreRefDirectiveExplanation {
            get {
                return ResourceManager.GetString("QuestionIgnoreRefDirectiveExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for ignoring a ref directive ?.
        /// </summary>
        public static string QuestionIgnoreRefDirectiveText {
            get {
                return ResourceManager.GetString("QuestionIgnoreRefDirectiveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for intentionally or blatantly ignoring a “boundary” call ?.
        /// </summary>
        public static string QuestionIgnoringBoundaryCallText {
            get {
                return ResourceManager.GetString("QuestionIgnoringBoundaryCallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for an illegal bludger bat or block ?.
        /// </summary>
        public static string QuestionIllegalBlockBatBludgerText {
            get {
                return ResourceManager.GetString("QuestionIllegalBlockBatBludgerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bludger may only be swat by beaters, and only with a held ball or if they are not still struck (so they become struck by a live bludger when swatting).
        /// </summary>
        public static string QuestionIllegalBludgerSwatExplanation {
            get {
                return ResourceManager.GetString("QuestionIllegalBludgerSwatExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for an illegal bludger swat ?.
        /// </summary>
        public static string QuestionIllegalBludgerSwatText {
            get {
                return ResourceManager.GetString("QuestionIllegalBludgerSwatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An helpless receiver is defined as a receiver who is in the process of catching a ball that is in the air..
        /// </summary>
        public static string QuestionIllegalContactHelplessReceiverExplanation {
            get {
                return ResourceManager.GetString("QuestionIllegalContactHelplessReceiverExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is a penalty for an illegal contact on a helpless receiver ?.
        /// </summary>
        public static string QuestionIllegalContactHelplessReceiverText {
            get {
                return ResourceManager.GetString("QuestionIllegalContactHelplessReceiverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for intentionally or egregiously illegally going or remaining out of bounds ?.
        /// </summary>
        public static string QuestionIllegalGoOutOfBoundText {
            get {
                return ResourceManager.GetString("QuestionIllegalGoOutOfBoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A hurdle is defined as jumping or diving fully over any person, and is not legal on a player that is standing up..
        /// </summary>
        public static string QuestionIllegalHurdlingExplanation {
            get {
                return ResourceManager.GetString("QuestionIllegalHurdlingExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for illegaly hurdling or attempting to hurdle ?.
        /// </summary>
        public static string QuestionIllegalHurdlingText {
            get {
                return ResourceManager.GetString("QuestionIllegalHurdlingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for an illegal immunity claim ?.
        /// </summary>
        public static string QuestionIllegalImmunityClaimText {
            get {
                return ResourceManager.GetString("QuestionIllegalImmunityClaimText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for an illegal interposition ?.
        /// </summary>
        public static string QuestionIllegalInterpositionText {
            get {
                return ResourceManager.GetString("QuestionIllegalInterpositionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for illegaly resetting an opponent&apos;s hoop ?.
        /// </summary>
        public static string QuestionIllegalResetOpponentHoopText {
            get {
                return ResourceManager.GetString("QuestionIllegalResetOpponentHoopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for an illegal reset ?.
        /// </summary>
        public static string QuestionIllegalResetText {
            get {
                return ResourceManager.GetString("QuestionIllegalResetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for an illegal second kick ?.
        /// </summary>
        public static string QuestionIllegalSecondKickText {
            get {
                return ResourceManager.GetString("QuestionIllegalSecondKickText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No penalty.
        /// </summary>
        public static string QuestionIllegalSetPlayerAnswer1 {
            get {
                return ResourceManager.GetString("QuestionIllegalSetPlayerAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnover and correct the team composition.
        /// </summary>
        public static string QuestionIllegalSetPlayerAnswer2 {
            get {
                return ResourceManager.GetString("QuestionIllegalSetPlayerAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue card for the speaking captain.
        /// </summary>
        public static string QuestionIllegalSetPlayerAnswer3 {
            get {
                return ResourceManager.GetString("QuestionIllegalSetPlayerAnswer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow card for the speaking captain.
        /// </summary>
        public static string QuestionIllegalSetPlayerAnswer4 {
            get {
                return ResourceManager.GetString("QuestionIllegalSetPlayerAnswer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red card for the speaking captain.
        /// </summary>
        public static string QuestionIllegalSetPlayerAnswer5 {
            get {
                return ResourceManager.GetString("QuestionIllegalSetPlayerAnswer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for a team that has an illegal set of player in play ?.
        /// </summary>
        public static string QuestionIllegalSetPlayerText {
            get {
                return ResourceManager.GetString("QuestionIllegalSetPlayerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat procedure.
        /// </summary>
        public static string QuestionIllegalSubstitutionAnswer1 {
            get {
                return ResourceManager.GetString("QuestionIllegalSubstitutionAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An illegal susbtitution must affect play, otherwise it is a substitution violation..
        /// </summary>
        public static string QuestionIllegalSubstitutionExplanation {
            get {
                return ResourceManager.GetString("QuestionIllegalSubstitutionExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for an illegal substitution ?.
        /// </summary>
        public static string QuestionIllegalSubstitutionText {
            get {
                return ResourceManager.GetString("QuestionIllegalSubstitutionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for an illegal bludger swat ?.
        /// </summary>
        public static string QuestionIllegalSwatBludgerText {
            get {
                return ResourceManager.GetString("QuestionIllegalSwatBludgerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for an illegal timeout request ?.
        /// </summary>
        public static string QuestionIllegalTimeoutRequestText {
            get {
                return ResourceManager.GetString("QuestionIllegalTimeoutRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for an illegal use of a ball of one&apos;s position ?.
        /// </summary>
        public static string QuestionIllegalUseOfBallText {
            get {
                return ResourceManager.GetString("QuestionIllegalUseOfBallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An immunity violation is defined as a player that legally claimed immunity, then did not correctly retrieved the third bludger.
        /// </summary>
        public static string QuestionImmunityViolationExplanation {
            get {
                return ResourceManager.GetString("QuestionImmunityViolationExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for an immunity violation ?.
        /// </summary>
        public static string QuestionImmunityViolationText {
            get {
                return ResourceManager.GetString("QuestionImmunityViolationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for an improper immunity claim ?.
        /// </summary>
        public static string QuestionImproperImmunityClaimText {
            get {
                return ResourceManager.GetString("QuestionImproperImmunityClaimText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an incoming beater was faulty but was retrieving the third bludger, .
        /// </summary>
        public static string QuestionInboundingProcedureViolationExplanation {
            get {
                return ResourceManager.GetString("QuestionInboundingProcedureViolationExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for an inbounding procedure violation ?.
        /// </summary>
        public static string QuestionInboundingProcedureViolationText {
            get {
                return ResourceManager.GetString("QuestionInboundingProcedureViolationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for an incidental interposition ball interference ?.
        /// </summary>
        public static string QuestionIncidentalBallInterferenceText {
            get {
                return ResourceManager.GetString("QuestionIncidentalBallInterferenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for an incidental interposition ball interference ?.
        /// </summary>
        public static string QuestionIncidentalInterpositionBallInterferenceText {
            get {
                return ResourceManager.GetString("QuestionIncidentalInterpositionBallInterferenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat procedure.
        /// </summary>
        public static string QuestionIntentionalFailKoProcedureAnswer1 {
            get {
                return ResourceManager.GetString("QuestionIntentionalFailKoProcedureAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for intentionally or repeatedly violating the knockout procedure ?.
        /// </summary>
        public static string QuestionIntentionalFailKoProcedureText {
            get {
                return ResourceManager.GetString("QuestionIntentionalFailKoProcedureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for an intentionnal natural motion violation ?.
        /// </summary>
        public static string QuestionIntentionalMotionViolationText {
            get {
                return ResourceManager.GetString("QuestionIntentionalMotionViolationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for illegally interacting with play while knocked out ?.
        /// </summary>
        public static string QuestionInteractingWhenKOText {
            get {
                return ResourceManager.GetString("QuestionInteractingWhenKOText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for illegally interacting with a knocked out player ?.
        /// </summary>
        public static string QuestionInteractKoPlayerText {
            get {
                return ResourceManager.GetString("QuestionInteractKoPlayerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for an interposition ball interference ?.
        /// </summary>
        public static string QuestionInterpositionBallInterferenceText {
            get {
                return ResourceManager.GetString("QuestionInterpositionBallInterferenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 10 meters.
        /// </summary>
        public static string QuestionKeeperLineMetersAnswer1 {
            get {
                return ResourceManager.GetString("QuestionKeeperLineMetersAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 11 meters.
        /// </summary>
        public static string QuestionKeeperLineMetersAnswer2 {
            get {
                return ResourceManager.GetString("QuestionKeeperLineMetersAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 12 meters.
        /// </summary>
        public static string QuestionKeeperLineMetersAnswer3 {
            get {
                return ResourceManager.GetString("QuestionKeeperLineMetersAnswer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At which distance is the keeper line from the midfield line ?.
        /// </summary>
        public static string QuestionKeeperLineMetersText {
            get {
                return ResourceManager.GetString("QuestionKeeperLineMetersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 10 yards.
        /// </summary>
        public static string QuestionKeeperLineYardAnswer1 {
            get {
                return ResourceManager.GetString("QuestionKeeperLineYardAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 11 yards.
        /// </summary>
        public static string QuestionKeeperLineYardAnswer2 {
            get {
                return ResourceManager.GetString("QuestionKeeperLineYardAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 12 yards.
        /// </summary>
        public static string QuestionKeeperLineYardAnswer3 {
            get {
                return ResourceManager.GetString("QuestionKeeperLineYardAnswer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At which distance is the keeper line from the midfield line ?.
        /// </summary>
        public static string QuestionKeeperLineYardText {
            get {
                return ResourceManager.GetString("QuestionKeeperLineYardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That player can block a bludger.
        /// </summary>
        public static string QuestionKeeperPowersAnswer1 {
            get {
                return ResourceManager.GetString("QuestionKeeperPowersAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That player can kick the ball any number of time.
        /// </summary>
        public static string QuestionKeeperPowersAnswer2 {
            get {
                return ResourceManager.GetString("QuestionKeeperPowersAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That player is immune to KO by bludgers.
        /// </summary>
        public static string QuestionKeeperPowersAnswer3 {
            get {
                return ResourceManager.GetString("QuestionKeeperPowersAnswer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That player gets the quaffle back if it goes out of bound after a save.
        /// </summary>
        public static string QuestionKeeperPowersAnswer4 {
            get {
                return ResourceManager.GetString("QuestionKeeperPowersAnswer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That player cannot be contacted, interacted with, or stolen the quaffle while he is the sole possessor of it.
        /// </summary>
        public static string QuestionKeeperPowersAnswer5 {
            get {
                return ResourceManager.GetString("QuestionKeeperPowersAnswer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are the keeper-specific powers ?.
        /// </summary>
        public static string QuestionKeeperPowersText {
            get {
                return ResourceManager.GetString("QuestionKeeperPowersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endlines are 30 meters.
        /// </summary>
        public static string QuestionLinesExternMetersAnswer1 {
            get {
                return ResourceManager.GetString("QuestionLinesExternMetersAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endlines are 33 meters.
        /// </summary>
        public static string QuestionLinesExternMetersAnswer2 {
            get {
                return ResourceManager.GetString("QuestionLinesExternMetersAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endlines are 36 meters.
        /// </summary>
        public static string QuestionLinesExternMetersAnswer3 {
            get {
                return ResourceManager.GetString("QuestionLinesExternMetersAnswer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidelines are 60 meters.
        /// </summary>
        public static string QuestionLinesExternMetersAnswer4 {
            get {
                return ResourceManager.GetString("QuestionLinesExternMetersAnswer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidelines are 63 meters.
        /// </summary>
        public static string QuestionLinesExternMetersAnswer5 {
            get {
                return ResourceManager.GetString("QuestionLinesExternMetersAnswer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidelines are 66 meters.
        /// </summary>
        public static string QuestionLinesExternMetersAnswer6 {
            get {
                return ResourceManager.GetString("QuestionLinesExternMetersAnswer6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are the length of the extern field lines ?.
        /// </summary>
        public static string QuestionLinesExternMetersText {
            get {
                return ResourceManager.GetString("QuestionLinesExternMetersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endlines are 30 yards.
        /// </summary>
        public static string QuestionLinesExternYardsAnswer1 {
            get {
                return ResourceManager.GetString("QuestionLinesExternYardsAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endlines are 33 yards.
        /// </summary>
        public static string QuestionLinesExternYardsAnswer2 {
            get {
                return ResourceManager.GetString("QuestionLinesExternYardsAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endlines are 36 yards.
        /// </summary>
        public static string QuestionLinesExternYardsAnswer3 {
            get {
                return ResourceManager.GetString("QuestionLinesExternYardsAnswer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidelines are 60 yards.
        /// </summary>
        public static string QuestionLinesExternYardsAnswer4 {
            get {
                return ResourceManager.GetString("QuestionLinesExternYardsAnswer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidelines are 63 yards.
        /// </summary>
        public static string QuestionLinesExternYardsAnswer5 {
            get {
                return ResourceManager.GetString("QuestionLinesExternYardsAnswer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidelines are 66 yards.
        /// </summary>
        public static string QuestionLinesExternYardsAnswer6 {
            get {
                return ResourceManager.GetString("QuestionLinesExternYardsAnswer6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are the length of the extern field lines ?.
        /// </summary>
        public static string QuestionLinesExternYardsText {
            get {
                return ResourceManager.GetString("QuestionLinesExternYardsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for a minor failure to avoid a propelled quaffle ?.
        /// </summary>
        public static string QuestionMinorAvoidQuaffleText {
            get {
                return ResourceManager.GetString("QuestionMinorAvoidQuaffleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for a minor illegal immunity claim ?.
        /// </summary>
        public static string QuestionMinorIllegalImmunityClaimText {
            get {
                return ResourceManager.GetString("QuestionMinorIllegalImmunityClaimText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for a minor illegal interposition ?.
        /// </summary>
        public static string QuestionMinorIllegalInterpositionText {
            get {
                return ResourceManager.GetString("QuestionMinorIllegalInterpositionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for moving a hoop intentionnaly ?.
        /// </summary>
        public static string QuestionMoveHoopIntentionnalyText {
            get {
                return ResourceManager.GetString("QuestionMoveHoopIntentionnalyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player with the least remaining time is released.
        /// </summary>
        public static string QuestionMultiplePlayersInBoxWhenScoreAnswer1 {
            get {
                return ResourceManager.GetString("QuestionMultiplePlayersInBoxWhenScoreAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both players are released.
        /// </summary>
        public static string QuestionMultiplePlayersInBoxWhenScoreAnswer2 {
            get {
                return ResourceManager.GetString("QuestionMultiplePlayersInBoxWhenScoreAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two players of the same team are in the penalty box serving a yellow penalty when their team get scored against :.
        /// </summary>
        public static string QuestionMultiplePlayersInBoxWhenScoreText {
            get {
                return ResourceManager.GetString("QuestionMultiplePlayersInBoxWhenScoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for an unintentionnal natural motion violation ?.
        /// </summary>
        public static string QuestionNaturalMotionViolationText {
            get {
                return ResourceManager.GetString("QuestionNaturalMotionViolationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for knowingly playing with a broken broom ?.
        /// </summary>
        public static string QuestionPlayBrokenBroomText {
            get {
                return ResourceManager.GetString("QuestionPlayBrokenBroomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for entering play without wearing mandatory equipment ?.
        /// </summary>
        public static string QuestionPlayIllegalEquipmentText {
            get {
                return ResourceManager.GetString("QuestionPlayIllegalEquipmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too long fingernails can be seen when the hand is palm up, for example..
        /// </summary>
        public static string QuestionPlayIllegalFingernailsExplanation {
            get {
                return ResourceManager.GetString("QuestionPlayIllegalFingernailsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for entering play with illegally long or sharp fingernails ?.
        /// </summary>
        public static string QuestionPlayIllegalFingernailsText {
            get {
                return ResourceManager.GetString("QuestionPlayIllegalFingernailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for illegally physically preventing the inbounding player from re-entering the pitch ?.
        /// </summary>
        public static string QuestionPreventOutOfBoundFromEnteringText {
            get {
                return ResourceManager.GetString("QuestionPreventOutOfBoundFromEnteringText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for removing a mandatory equipment while in play ?.
        /// </summary>
        public static string QuestionRemoveIllegalEquipmentText {
            get {
                return ResourceManager.GetString("QuestionRemoveIllegalEquipmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for the repeated use of explicit or vulgar language ?.
        /// </summary>
        public static string QuestionRepeatVulgarLanguageText {
            get {
                return ResourceManager.GetString("QuestionRepeatVulgarLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for a seeker false start ?.
        /// </summary>
        public static string QuestionSeekerFalseStartText {
            get {
                return ResourceManager.GetString("QuestionSeekerFalseStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for propelling a ball with the intent of sending any ball out of bounds ?.
        /// </summary>
        public static string QuestionSendingBallOutOfBoundText {
            get {
                return ResourceManager.GetString("QuestionSendingBallOutOfBoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for an unintentionnal sideline interference ?.
        /// </summary>
        public static string QuestionSideLineInterferenceText {
            get {
                return ResourceManager.GetString("QuestionSideLineInterferenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This penalty may be reduced.
        /// </summary>
        public static string QuestionStandardContactPenaltyAnswer1 {
            get {
                return ResourceManager.GetString("QuestionStandardContactPenaltyAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This penalty may be augmented.
        /// </summary>
        public static string QuestionStandardContactPenaltyAnswer2 {
            get {
                return ResourceManager.GetString("QuestionStandardContactPenaltyAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The penalty shall be reduced to a back to hoops if the fouling player immediatly correct his position, and augmented to a red card if the play was egregious..
        /// </summary>
        public static string QuestionStandardContactPenaltyExplanation {
            get {
                return ResourceManager.GetString("QuestionStandardContactPenaltyExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for a standard contact violation ?.
        /// </summary>
        public static string QuestionStandardContactPenaltyText {
            get {
                return ResourceManager.GetString("QuestionStandardContactPenaltyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for a struck beater violation.
        /// </summary>
        public static string QuestionStruckBeaterViolationText {
            get {
                return ResourceManager.GetString("QuestionStruckBeaterViolationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat procedure.
        /// </summary>
        public static string QuestionSubstitutionViolationAnswer1 {
            get {
                return ResourceManager.GetString("QuestionSubstitutionViolationAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A substitution violation is defined as an illegal substitution that did not affect play yet..
        /// </summary>
        public static string QuestionSubstitutionViolationExplanation {
            get {
                return ResourceManager.GetString("QuestionSubstitutionViolationExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for a substitution violation ?.
        /// </summary>
        public static string QuestionSubstitutionViolationText {
            get {
                return ResourceManager.GetString("QuestionSubstitutionViolationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string QuestionTeamCompositionAnswer1 {
            get {
                return ResourceManager.GetString("QuestionTeamCompositionAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string QuestionTeamCompositionAnswer2 {
            get {
                return ResourceManager.GetString("QuestionTeamCompositionAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        public static string QuestionTeamCompositionAnswer3 {
            get {
                return ResourceManager.GetString("QuestionTeamCompositionAnswer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        public static string QuestionTeamCompositionAnswer4 {
            get {
                return ResourceManager.GetString("QuestionTeamCompositionAnswer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the lower and upper limit of the number of player in a team ?.
        /// </summary>
        public static string QuestionTeamCompositionText {
            get {
                return ResourceManager.GetString("QuestionTeamCompositionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team must play with fewer than the necessary amount of player.
        /// </summary>
        public static string QuestionTeamPenaltyAnswer1 {
            get {
                return ResourceManager.GetString("QuestionTeamPenaltyAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team must forfeit.
        /// </summary>
        public static string QuestionTeamPenaltyAnswer2 {
            get {
                return ResourceManager.GetString("QuestionTeamPenaltyAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is also true if the team has more than 7 players, but cannot respect the 4-maximum rule..
        /// </summary>
        public static string QuestionTeamPenaltyExplanation {
            get {
                return ResourceManager.GetString("QuestionTeamPenaltyExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What happens when a team falls below the necessary number of player during a game ?.
        /// </summary>
        public static string QuestionTeamPenaltyText {
            get {
                return ResourceManager.GetString("QuestionTeamPenaltyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double bludger turnover.
        /// </summary>
        public static string QuestionThirdBludgerInterferenceAnswer1 {
            get {
                return ResourceManager.GetString("QuestionThirdBludgerInterferenceAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the turned over bludger should usually be the one that was on the ground..
        /// </summary>
        public static string QuestionThirdBludgerInterferenceExplanation {
            get {
                return ResourceManager.GetString("QuestionThirdBludgerInterferenceExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for a third bludger interference ?.
        /// </summary>
        public static string QuestionThirdBludgerInterferenceText {
            get {
                return ResourceManager.GetString("QuestionThirdBludgerInterferenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ball is placed at the hoops of the fouled team.
        /// </summary>
        public static string QuestionTurnoverWhenNoElligibleAnswer1 {
            get {
                return ResourceManager.GetString("QuestionTurnoverWhenNoElligibleAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ball is unplayable until the fouled team plays it.
        /// </summary>
        public static string QuestionTurnoverWhenNoElligibleAnswer2 {
            get {
                return ResourceManager.GetString("QuestionTurnoverWhenNoElligibleAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The turnover is cancelled.
        /// </summary>
        public static string QuestionTurnoverWhenNoElligibleAnswer3 {
            get {
                return ResourceManager.GetString("QuestionTurnoverWhenNoElligibleAnswer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What happens when a turnover is called, but no elligible player may receive the turned-over ball ?.
        /// </summary>
        public static string QuestionTurnoverWhenNoElligibleText {
            get {
                return ResourceManager.GetString("QuestionTurnoverWhenNoElligibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for an unsportsmanlike conduct ?.
        /// </summary>
        public static string QuestionUnsportsmanlikeConductText {
            get {
                return ResourceManager.GetString("QuestionUnsportsmanlikeConductText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for using a ball to interact with the snitch runner ?.
        /// </summary>
        public static string QuestionUseBallInteractSnitchText {
            get {
                return ResourceManager.GetString("QuestionUseBallInteractSnitchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player must sub and correct his equipment before entering play.
        /// </summary>
        public static string QuestionUseIllegalEquipmentAnswer1 {
            get {
                return ResourceManager.GetString("QuestionUseIllegalEquipmentAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for playing with an illegal equipment ?.
        /// </summary>
        public static string QuestionUseIllegalEquipmentText {
            get {
                return ResourceManager.GetString("QuestionUseIllegalEquipmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player must sub and correct his equipment before entering play.
        /// </summary>
        public static string QuestionUseSpecificalIllegalEquipmentAnswer1 {
            get {
                return ResourceManager.GetString("QuestionUseSpecificalIllegalEquipmentAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for using an equipment that was specified as illegal by the tournament organisator ?.
        /// </summary>
        public static string QuestionUseSpecificalIllegalEquipmentText {
            get {
                return ResourceManager.GetString("QuestionUseSpecificalIllegalEquipmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for a reckless contact ?.
        /// </summary>
        public static string QuestionViolentContactText {
            get {
                return ResourceManager.GetString("QuestionViolentContactText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the penalty for a violent or egregious kick ?.
        /// </summary>
        public static string QuestionViolentKickText {
            get {
                return ResourceManager.GetString("QuestionViolentKickText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player goes to the penalty box.
        /// </summary>
        public static string QuestionYellowDuringAdvantageAnswer1 {
            get {
                return ResourceManager.GetString("QuestionYellowDuringAdvantageAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player must go back to hoops.
        /// </summary>
        public static string QuestionYellowDuringAdvantageAnswer2 {
            get {
                return ResourceManager.GetString("QuestionYellowDuringAdvantageAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player keeps playing.
        /// </summary>
        public static string QuestionYellowDuringAdvantageAnswer3 {
            get {
                return ResourceManager.GetString("QuestionYellowDuringAdvantageAnswer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since the foul happened before the score, it would have released the player. In this case, the player is not sent to the penalty box and keeps playing..
        /// </summary>
        public static string QuestionYellowDuringAdvantageExplanation {
            get {
                return ResourceManager.GetString("QuestionYellowDuringAdvantageExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A player do a blue or yellow card offense causing an advantage. After the fouled team scores, the referee gives the card to the player..
        /// </summary>
        public static string QuestionYellowDuringAdvantageText {
            get {
                return ResourceManager.GetString("QuestionYellowDuringAdvantageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red card.
        /// </summary>
        public static string RedCard {
            get {
                return ResourceManager.GetString("RedCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnover.
        /// </summary>
        public static string Turnover {
            get {
                return ResourceManager.GetString("Turnover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow card.
        /// </summary>
        public static string YellowCard {
            get {
                return ResourceManager.GetString("YellowCard", resourceCulture);
            }
        }
    }
}
