//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QRefTrain3.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string CreateAccount_Confirmpassword {
            get {
                return ResourceManager.GetString("CreateAccount_Confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account created, you can now use the website. Please confirm your account under three days by clicking on the link we sent you by mail. And welcome ! :).
        /// </summary>
        public static string CreateAccount_CreationConfirmation {
            get {
                return ResourceManager.GetString("CreateAccount_CreationConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account using this mail already exists..
        /// </summary>
        public static string CreateAccount_ErrorMailAlreadyUser {
            get {
                return ResourceManager.GetString("CreateAccount_ErrorMailAlreadyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when sending the mail. Please contact the support if this error happens again..
        /// </summary>
        public static string CreateAccount_ErrorMailInnaccessible {
            get {
                return ResourceManager.GetString("CreateAccount_ErrorMailInnaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is not available..
        /// </summary>
        public static string CreateAccount_ErrorUsernameAlreadyUser {
            get {
                return ResourceManager.GetString("CreateAccount_ErrorUsernameAlreadyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your registration, please click on the below link to confirm your mail: &lt;a href=\&quot;{0}\&quot; title=\&quot;User Email Confirm\&quot;&gt;{1}&lt;/a&gt;..
        /// </summary>
        public static string CreateAccount_Mailbody {
            get {
                return ResourceManager.GetString("CreateAccount_Mailbody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        public static string CreateAccount_NewAccountPrompt {
            get {
                return ResourceManager.GetString("CreateAccount_NewAccountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account validated. Happy refing !.
        /// </summary>
        public static string CreateAccount_ValidationConfirmation {
            get {
                return ResourceManager.GetString("CreateAccount_ValidationConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error when validating the test. Please contact the support for more information..
        /// </summary>
        public static string Error_QuizError {
            get {
                return ResourceManager.GetString("Error_QuizError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HomePage.
        /// </summary>
        public static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGB specific questions only.
        /// </summary>
        public static string Homepage_NGBSpecificPrompt {
            get {
                return ResourceManager.GetString("Homepage_NGBSpecificPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training test.
        /// </summary>
        public static string Homepage_ParameterPrompt {
            get {
                return ResourceManager.GetString("Homepage_ParameterPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website is in beta..
        /// </summary>
        public static string Homepage_ReminderBeta01 {
            get {
                return ResourceManager.GetString("Homepage_ReminderBeta01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For any question or remark, please contact qreftrain@gmail.com or visit .
        /// </summary>
        public static string Homepage_ReminderBeta02 {
            get {
                return ResourceManager.GetString("Homepage_ReminderBeta02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to our subreddit.
        /// </summary>
        public static string Homepage_ReminderBeta03 {
            get {
                return ResourceManager.GetString("Homepage_ReminderBeta03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume test.
        /// </summary>
        public static string Homepage_ResumeQuiz {
            get {
                return ResourceManager.GetString("Homepage_ResumeQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the test.
        /// </summary>
        public static string Homepage_StartQuizz {
            get {
                return ResourceManager.GetString("Homepage_StartQuizz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official test.
        /// </summary>
        public static string Homepage_TestPrompt {
            get {
                return ResourceManager.GetString("Homepage_TestPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already connected as :.
        /// </summary>
        public static string Login_AlreadyConnected {
            get {
                return ResourceManager.GetString("Login_AlreadyConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Login_ConfirmPassword {
            get {
                return ResourceManager.GetString("Login_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string Login_CreateAccount {
            get {
                return ResourceManager.GetString("Login_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to disconnect ?.
        /// </summary>
        public static string Login_DisconnectPrompt {
            get {
                return ResourceManager.GetString("Login_DisconnectPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Login_Email {
            get {
                return ResourceManager.GetString("Login_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your informations..
        /// </summary>
        public static string Login_EnterInformationPrompt {
            get {
                return ResourceManager.GetString("Login_EnterInformationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code must be 6 character.
        /// </summary>
        public static string Login_Errorcode {
            get {
                return ResourceManager.GetString("Login_Errorcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string Login_Errorconfirmationpassword {
            get {
                return ResourceManager.GetString("Login_Errorconfirmationpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name or Password incorrect.
        /// </summary>
        public static string Login_ErrorInformations {
            get {
                return ResourceManager.GetString("Login_ErrorInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address.
        /// </summary>
        public static string Login_Errormail {
            get {
                return ResourceManager.GetString("Login_Errormail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be 4 character long.
        /// </summary>
        public static string Login_Errorname {
            get {
                return ResourceManager.GetString("Login_Errorname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be 6 character long.
        /// </summary>
        public static string Login_Errorpassword {
            get {
                return ResourceManager.GetString("Login_Errorpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Login_Name {
            get {
                return ResourceManager.GetString("Login_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string Login_NewPassword {
            get {
                return ResourceManager.GetString("Login_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset code.
        /// </summary>
        public static string Login_ResetCode {
            get {
                return ResourceManager.GetString("Login_ResetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need a new password ?.
        /// </summary>
        public static string Login_Resetpassword {
            get {
                return ResourceManager.GetString("Login_Resetpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string NGBs_All {
            get {
                return ResourceManager.GetString("NGBs_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada.
        /// </summary>
        public static string NGBs_Canada {
            get {
                return ResourceManager.GetString("NGBs_Canada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        public static string NGBs_Europe {
            get {
                return ResourceManager.GetString("NGBs_Europe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usa.
        /// </summary>
        public static string NGBs_Usa {
            get {
                return ResourceManager.GetString("NGBs_Usa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Question_Advanced {
            get {
                return ResourceManager.GetString("Question_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player should touch the round part of the hoop..
        /// </summary>
        public static string Question_Sample_Answer1 {
            get {
                return ResourceManager.GetString("Question_Sample_Answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player should remove their broom before touching the hoop..
        /// </summary>
        public static string Question_Sample_Answer2 {
            get {
                return ResourceManager.GetString("Question_Sample_Answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player should grab the hoop instead of touching it..
        /// </summary>
        public static string Question_Sample_Answer3 {
            get {
                return ResourceManager.GetString("Question_Sample_Answer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing is missing..
        /// </summary>
        public static string Question_Sample_Answer4 {
            get {
                return ResourceManager.GetString("Question_Sample_Answer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player should have the broom removed when touching the hoop..
        /// </summary>
        public static string Question_Sample_Explanation {
            get {
                return ResourceManager.GetString("Question_Sample_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is missing from this procedure ?.
        /// </summary>
        public static string Question_Sample_Text {
            get {
                return ResourceManager.GetString("Question_Sample_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question title.
        /// </summary>
        public static string Question_Sample_Title {
            get {
                return ResourceManager.GetString("Question_Sample_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeker.
        /// </summary>
        public static string Question_Seeker {
            get {
                return ResourceManager.GetString("Question_Seeker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Answers.
        /// </summary>
        public static string Quiz_ValidateAnswer {
            get {
                return ResourceManager.GetString("Quiz_ValidateAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password reset was requested on this account. Please use the code : {0} to change the password. If you did not request a reset, please ignore this mail..
        /// </summary>
        public static string ResetPassword_Mailbody {
            get {
                return ResourceManager.GetString("ResetPassword_Mailbody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your mail..
        /// </summary>
        public static string Resetpassword_Prompt {
            get {
                return ResourceManager.GetString("Resetpassword_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advantage.
        /// </summary>
        public static string Subject_Advantage {
            get {
                return ResourceManager.GetString("Subject_Advantage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Subject_Contacts {
            get {
                return ResourceManager.GetString("Subject_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions.
        /// </summary>
        public static string Subject_Definition {
            get {
                return ResourceManager.GetString("Subject_Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delayed penalty.
        /// </summary>
        public static string Subject_DelayedPenalty {
            get {
                return ResourceManager.GetString("Subject_DelayedPenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay of game.
        /// </summary>
        public static string Subject_DelayOfGame {
            get {
                return ResourceManager.GetString("Subject_DelayOfGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &amp; Equipments.
        /// </summary>
        public static string Subject_FieldsAndEquipment {
            get {
                return ResourceManager.GetString("Subject_FieldsAndEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immunity&amp;Guarding.
        /// </summary>
        public static string Subject_ImmunityAndGuarding {
            get {
                return ResourceManager.GetString("Subject_ImmunityAndGuarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keeper.
        /// </summary>
        public static string Subject_Keeper {
            get {
                return ResourceManager.GetString("Subject_Keeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knockout.
        /// </summary>
        public static string Subject_KO {
            get {
                return ResourceManager.GetString("Subject_KO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No harm no foul.
        /// </summary>
        public static string Subject_NHNF {
            get {
                return ResourceManager.GetString("Subject_NHNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Subject_Other {
            get {
                return ResourceManager.GetString("Subject_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boundaries and play.
        /// </summary>
        public static string Subject_OutOfBoundaries {
            get {
                return ResourceManager.GetString("Subject_OutOfBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string Subject_Process {
            get {
                return ResourceManager.GetString("Subject_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Subject_Reset {
            get {
                return ResourceManager.GetString("Subject_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoring.
        /// </summary>
        public static string Subject_Scoring {
            get {
                return ResourceManager.GetString("Subject_Scoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snitch play.
        /// </summary>
        public static string Subject_SnitchPlay {
            get {
                return ResourceManager.GetString("Subject_SnitchPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substitution.
        /// </summary>
        public static string Subject_Substitution {
            get {
                return ResourceManager.GetString("Subject_Substitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a language.
        /// </summary>
        public static string TopDiv_ChooseLanguage {
            get {
                return ResourceManager.GetString("TopDiv_ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string TopDiv_Login {
            get {
                return ResourceManager.GetString("TopDiv_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string TopDiv_Logout {
            get {
                return ResourceManager.GetString("TopDiv_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string TopDiv_Questions {
            get {
                return ResourceManager.GetString("TopDiv_Questions", resourceCulture);
            }
        }
    }
}
