//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QRefTrain3.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HomePage.
        /// </summary>
        public static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGB specific questions only.
        /// </summary>
        public static string Homepage_NGBSpecificPrompt {
            get {
                return ResourceManager.GetString("Homepage_NGBSpecificPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a training test.
        /// </summary>
        public static string Homepage_ParameterPrompt {
            get {
                return ResourceManager.GetString("Homepage_ParameterPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;This website is in beta.&lt;/strong&gt; For any question or remark, please contact qreftrain@gmail.com or visit &lt;a href=&quot;https://www.reddit.com/r/QuidditchRefTraining/&quot; target=&quot;_blank&quot;&gt;our subreddit&lt;/a&gt;.
        /// </summary>
        public static string Homepage_ReminderBeta {
            get {
                return ResourceManager.GetString("Homepage_ReminderBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the quiz.
        /// </summary>
        public static string Homepage_StartQuizz {
            get {
                return ResourceManager.GetString("Homepage_StartQuizz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take an official test..
        /// </summary>
        public static string Homepage_TestPrompt {
            get {
                return ResourceManager.GetString("Homepage_TestPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string NGBs_All {
            get {
                return ResourceManager.GetString("NGBs_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada.
        /// </summary>
        public static string NGBs_Canada {
            get {
                return ResourceManager.GetString("NGBs_Canada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        public static string NGBs_Europe {
            get {
                return ResourceManager.GetString("NGBs_Europe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usa.
        /// </summary>
        public static string NGBs_Usa {
            get {
                return ResourceManager.GetString("NGBs_Usa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Question_Advanced {
            get {
                return ResourceManager.GetString("Question_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string Question_Basic {
            get {
                return ResourceManager.GetString("Question_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beater.
        /// </summary>
        public static string Question_Beater {
            get {
                return ResourceManager.GetString("Question_Beater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaser.
        /// </summary>
        public static string Question_Chaser {
            get {
                return ResourceManager.GetString("Question_Chaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Question_Contact {
            get {
                return ResourceManager.GetString("Question_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Question_Other {
            get {
                return ResourceManager.GetString("Question_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string Question_Process {
            get {
                return ResourceManager.GetString("Question_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player should touch the round part of the hoop..
        /// </summary>
        public static string Question_Sample_Answer1 {
            get {
                return ResourceManager.GetString("Question_Sample_Answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player should remove their broom before touching the hoop..
        /// </summary>
        public static string Question_Sample_Answer2 {
            get {
                return ResourceManager.GetString("Question_Sample_Answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player should grab the hoop instead of touching it..
        /// </summary>
        public static string Question_Sample_Answer3 {
            get {
                return ResourceManager.GetString("Question_Sample_Answer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing is missing..
        /// </summary>
        public static string Question_Sample_Answer4 {
            get {
                return ResourceManager.GetString("Question_Sample_Answer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player should have the broom removed when touching the hoop..
        /// </summary>
        public static string Question_Sample_Explanation {
            get {
                return ResourceManager.GetString("Question_Sample_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is missing from this procedure ?.
        /// </summary>
        public static string Question_Sample_Text {
            get {
                return ResourceManager.GetString("Question_Sample_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question title.
        /// </summary>
        public static string Question_Sample_Title {
            get {
                return ResourceManager.GetString("Question_Sample_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeker.
        /// </summary>
        public static string Question_Seeker {
            get {
                return ResourceManager.GetString("Question_Seeker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Answers.
        /// </summary>
        public static string Quiz_ValidateAnswer {
            get {
                return ResourceManager.GetString("Quiz_ValidateAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a language.
        /// </summary>
        public static string TopDiv_ChooseLanguage {
            get {
                return ResourceManager.GetString("TopDiv_ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string TopDiv_Login {
            get {
                return ResourceManager.GetString("TopDiv_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string TopDiv_Logout {
            get {
                return ResourceManager.GetString("TopDiv_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string TopDiv_Questions {
            get {
                return ResourceManager.GetString("TopDiv_Questions", resourceCulture);
            }
        }
    }
}
